# Generated by Django 5.1.6 on 2025-03-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_dish_image_profile_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
